import type { JxProtocolDefinition } from './types'

export const JX_V225_BUILTIN: JxProtocolDefinition = {
  schemaVersion: '1.0.0',
  protocolId: 'jx-v2.25-core',
  protocolName: '玖行协议V2.25',
  version: '2.25.0',
  source: 'builtin',
  vendor: 'jiuxing',
  description: '内置 V2.25 核心命令',
  commandCatalog: {
    '0x01': {
      cmd: '0x01',
      name: '桩请求连接',
      direction: 'up',
      requiredParams: ['timeTag', 'keyVersion', 'checkCipher', 'protocolVersion'],
    },
    '0x02': {
      cmd: '0x02',
      name: '请求连接结果',
      direction: 'down',
      requiredParams: ['timeTag', 'allowFlag'],
      optionalParams: ['rejectReason', 'qrSegments'],
    },
    '0x03': {
      cmd: '0x03',
      name: '登录信息',
      direction: 'up',
      requiredParams: ['timeTag', 'pileModel', 'heartbeatPeriodSec'],
    },
    '0x04': {
      cmd: '0x04',
      name: '请求连接结果',
      direction: 'down',
      requiredParams: ['timeTag', 'allowFlag'],
      optionalParams: ['rejectReason'],
    },
    '0x05': { cmd: '0x05', name: '请求对时', direction: 'up', requiredParams: ['timeTag'] },
    '0x06': { cmd: '0x06', name: '对时', direction: 'down', requiredParams: ['timeTag', 'syncTime'] },
    '0x07': {
      cmd: '0x07',
      name: '回复对时',
      direction: 'up',
      requiredParams: ['timeTag', 'syncResult'],
      optionalParams: ['syncFailReason'],
    },
    '0x0b': { cmd: '0x0b', name: '平台心跳', direction: 'down', requiredParams: ['timeTag'] },
    '0x0c': { cmd: '0x0c', name: '桩心跳', direction: 'up', requiredParams: ['timeTag'] },
    '0x1f': {
      cmd: '0x1f',
      name: '平台下发充电命令',
      direction: 'down',
      requiredParams: ['timeTag', 'gunNo', 'orderNo', 'userId', 'controlMode', 'controlParam'],
      optionalParams: ['userType', 'orgCode', 'chargeMode', 'startMode', 'scheduleStartTime'],
      resultFields: ['executeResult', 'failReason'],
    },
    '0x20': {
      cmd: '0x20',
      name: '桩回复充电命令',
      direction: 'up',
      requiredParams: ['timeTag', 'gunNo', 'orderNo', 'executeResult'],
      optionalParams: ['failReason'],
    },
    '0x21': {
      cmd: '0x21',
      name: '桩启动充电结果',
      direction: 'up',
      requiredParams: ['timeTag', 'gunNo', 'orderNo', 'startResult'],
      optionalParams: ['failReason'],
    },
    '0x22': {
      cmd: '0x22',
      name: '平台回复桩启动结果',
      direction: 'down',
      requiredParams: ['timeTag', 'gunNo', 'orderNo', 'ackResult'],
    },
    '0x25': {
      cmd: '0x25',
      name: '充电信息',
      direction: 'up',
      requiredParams: ['timeTag', 'gunNo', 'orderNo', 'chargeEnergy', 'chargeAmount'],
      optionalParams: ['chargeVoltage', 'chargeCurrent', 'segments'],
    },
    '0x30': {
      cmd: '0x30',
      name: 'BMS信息',
      direction: 'up',
      requiredParams: ['timeTag', 'gunNo', 'bclVoltageReq', 'bclCurrentReq', 'bcsVoltage', 'bcsCurrent', 'soc'],
    },
    '0x26': {
      cmd: '0x26',
      name: '停止充电',
      direction: 'down',
      requiredParams: ['timeTag', 'gunNo'],
      optionalParams: ['orderNo'],
    },
    '0x27': {
      cmd: '0x27',
      name: '回复停止充电',
      direction: 'up',
      requiredParams: ['timeTag', 'gunNo', 'orderNo', 'stopResult'],
    },
    '0x19': {
      cmd: '0x19',
      name: '卡鉴权',
      direction: 'up',
      requiredParams: ['timeTag', 'cardNo', 'gunNo'],
    },
    '0x1a': {
      cmd: '0x1a',
      name: '回复卡鉴权',
      direction: 'down',
      requiredParams: ['timeTag', 'cardNo', 'allowChargeFlag'],
      optionalParams: ['denyReason', 'orderNo', 'accountBalance'],
    },
    '0x40': { cmd: '0x40', name: 'VIN鉴权', direction: 'up', requiredParams: ['timeTag', 'vin', 'gunNo', 'orderNo'] },
    '0x41': {
      cmd: '0x41',
      name: '回复VIN鉴权',
      direction: 'down',
      requiredParams: ['timeTag', 'vin', 'allowChargeFlag'],
      optionalParams: ['denyReason', 'orderNo'],
    },
    '0x46': {
      cmd: '0x46',
      name: '插枪上报VIN',
      direction: 'up',
      requiredParams: ['timeTag', 'gunNo', 'vin'],
      optionalParams: ['orderNo'],
    },
    '0x47': {
      cmd: '0x47',
      name: '回复插枪上报VIN',
      direction: 'down',
      requiredParams: ['timeTag', 'vinAckResult'],
      optionalParams: ['vin', 'gunNo'],
    },
    '0x59': {
      cmd: '0x59',
      name: 'VIN启动请求',
      direction: 'down',
      requiredParams: ['timeTag', 'gunNo', 'orderNo'],
    },
    '0x5b': {
      cmd: '0x5b',
      name: 'VIN启动应答',
      direction: 'up',
      requiredParams: ['timeTag', 'gunNo', 'orderNo', 'result'],
      optionalParams: ['failReason'],
    },
    '0x23': {
      cmd: '0x23',
      name: '最新充电订单',
      direction: 'up',
      requiredParams: ['timeTag', 'gunNo', 'recordIndex', 'orderNo'],
      optionalParams: ['segments', 'vin'],
    },
    '0x33': {
      cmd: '0x33',
      name: '历史充电订单',
      direction: 'up',
      requiredParams: ['timeTag', 'gunNo', 'recordIndex', 'orderNo'],
      optionalParams: ['segments', 'vin'],
    },
    '0x61': {
      cmd: '0x61',
      name: '回复单条订单',
      direction: 'up',
      requiredParams: ['timeTag', 'existFlag'],
      optionalParams: ['orderNo', 'detail'],
    },
  },
  flowTemplates: [
    {
      flowId: 'login-auth',
      name: '链接认证登录流程',
      version: '1.0.0',
      requiresCommands: ['0x01', '0x02', '0x03', '0x04'],
      requiresParams: ['timeTag'],
      steps: [
        { id: 's1', type: 'expect', cmd: '0x01', timeoutMs: 3000 },
        { id: 's2', type: 'send', cmd: '0x02' },
        { id: 's3', type: 'expect', cmd: '0x03', timeoutMs: 3000 },
        { id: 's4', type: 'send', cmd: '0x04' },
      ],
    },
    {
      flowId: 'remote-start',
      name: '远端控制启动流程',
      version: '1.0.0',
      requiresCommands: ['0x1f', '0x20', '0x21', '0x22'],
      requiresParams: ['gunNo', 'orderNo', 'controlMode', 'controlParam'],
      steps: [
        { id: 's1', type: 'send', cmd: '0x1f' },
        { id: 's2', type: 'expect', cmd: '0x20', timeoutMs: 3000 },
        { id: 's3', type: 'expect', cmd: '0x21', timeoutMs: 5000 },
        { id: 's4', type: 'send', cmd: '0x22' },
        { id: 's5', type: 'emitState', statePatch: { pileStatus: 'charging', gunStatus: 'charging' } },
      ],
    },
    {
      flowId: 'scan-qr-remote-start',
      name: '扫码远程启动流程',
      version: '1.0.0',
      requiresCommands: ['0x1f', '0x20', '0x21', '0x22'],
      requiresParams: ['gunNo', 'orderNo'],
      steps: [
        { id: 's1', type: 'expect', cmd: '0x1f', timeoutMs: 60000 },
        { id: 's2', type: 'send', cmd: '0x20' },
        { id: 's3', type: 'send', cmd: '0x21' },
        { id: 's4', type: 'expect', cmd: '0x22', timeoutMs: 5000 },
        { id: 's5', type: 'emitState', statePatch: { pileStatus: 'charging', gunStatus: 'charging' } },
      ],
    },
    {
      flowId: 'card-start',
      name: '卡启动流程',
      version: '1.0.0',
      requiresCommands: ['0x19', '0x1a', '0x21', '0x22'],
      requiresParams: ['cardNo', 'gunNo'],
      steps: [
        { id: 's1', type: 'send', cmd: '0x19' },
        { id: 's2', type: 'expect', cmd: '0x1a', timeoutMs: 15000 },
        { id: 's3', type: 'expect', cmd: '0x21', timeoutMs: 5000 },
        { id: 's4', type: 'send', cmd: '0x22' },
        { id: 's5', type: 'emitState', statePatch: { pileStatus: 'charging', gunStatus: 'charging' } },
      ],
    },
    {
      flowId: 'vin-local-start',
      name: '本地VIN启动流程',
      version: '1.0.0',
      requiresCommands: ['0x46', '0x47', '0x40', '0x41', '0x1f', '0x20', '0x21', '0x22'],
      requiresParams: ['vin', 'gunNo', 'orderNo'],
      steps: [
        { id: 's1', type: 'send', cmd: '0x46' },
        { id: 's2', type: 'expect', cmd: '0x47', timeoutMs: 3000 },
        { id: 's3', type: 'send', cmd: '0x40' },
        { id: 's4', type: 'expect', cmd: '0x41', timeoutMs: 3000 },
        { id: 's5', type: 'send', cmd: '0x1f' },
        { id: 's6', type: 'expect', cmd: '0x20', timeoutMs: 3000 },
        { id: 's7', type: 'expect', cmd: '0x21', timeoutMs: 5000 },
        { id: 's8', type: 'send', cmd: '0x22' },
      ],
    },
    {
      flowId: 'remote-start-vin-auth',
      name: '远端控制启动VIN鉴权流程',
      version: '1.0.0',
      requiresCommands: ['0x40', '0x41', '0x21', '0x22'],
      requiresParams: ['vin', 'gunNo', 'orderNo'],
      steps: [
        { id: 's1', type: 'send', cmd: '0x40' },
        { id: 's2', type: 'expect', cmd: '0x41', timeoutMs: 3000 },
        { id: 's3', type: 'branch', by: 'allowChargeFlag', cases: { '1': 'pass', '2': 'deny' } },
        { id: 's4', type: 'expect', cmd: '0x21', timeoutMs: 5000 },
        { id: 's5', type: 'send', cmd: '0x22' },
      ],
    },
    {
      flowId: 'scan-qr-vin-start',
      name: '扫码VIN启动流程',
      version: '1.0.0',
      requiresCommands: ['0x59', '0x5b', '0x40', '0x41', '0x21', '0x22'],
      requiresParams: ['gunNo', 'orderNo', 'vin'],
      steps: [
        { id: 's1', type: 'expect', cmd: '0x59', timeoutMs: 30000 },
        { id: 's2', type: 'send', cmd: '0x5b' },
        { id: 's3', type: 'send', cmd: '0x40' },
        { id: 's4', type: 'expect', cmd: '0x41', timeoutMs: 15000 },
        { id: 's5', type: 'expect', cmd: '0x21', timeoutMs: 5000 },
        { id: 's6', type: 'send', cmd: '0x22' },
      ],
    },
  ],
}

/** V2.24：与 V2.25 命令表/流程一致，`0x23/0x33` 订单体字段布局见 `玖行桩协议2.24.md` 表-3.10.1。 */
export const JX_V224_BUILTIN: JxProtocolDefinition = {
  ...JX_V225_BUILTIN,
  protocolId: 'jx-v2.24-core',
  protocolName: '玖行协议V2.24',
  version: '2.24.0',
  description:
    '内置 V2.24 核心命令（0x23 含充电卡余额；起止电量与分时电量为 4 字节小端、0.0001kWh，与平台 CM23Data224 一致）',
}

